apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registrypvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: managed-nfs-storage
